name: qp_xt
version: 0.0.2+2
description: Quick Programing Extensions
homepage: https://github.com/rey-xi/qp_xt
repository: https://github.com/rey-xi/qp_xt

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
